# encoding: utf-8

TEST = [
 [799304208,"setecientos noventa y nueve millones trescientos cuatro mil doscientos ocho"],
 [949531602,"novecientos cuarenta y nueve millones quinientos treinta y un mil seiscientos dos"],
 [610860035,"seiscientos diez millones ochocientos sesenta mil treinta y cinco"],
 [785329085,"setecientos ochenta y cinco millones trescientos veintinueve mil ochenta y cinco"],
 [568955016,"quinientos sesenta y ocho millones novecientos cincuenta y cinco mil dieciseis"],
 [409924125,"cuatrocientos nueve millones novecientos veinticuatro mil ciento veinticinco"],
 [317296897,"trescientos diecisiete millones doscientos noventa y seis mil ochocientos noventa y siete"],
 [4019439, "cuatro millones diecinueve mil cuatrocientos treinta y nueve"],
 [248174350,"doscientos cuarenta y ocho millones ciento setenta y cuatro mil trescientos cincuenta"],
 [324936069,"trescientos veinticuatro millones novecientos treinta y seis mil sesenta y nueve"],
 [123513770,"ciento veintitres millones quinientos trece mil setecientos setenta"],
 [928673320,"novecientos veintiocho millones seiscientos setenta y tres mil trescientos veinte"],
 [452976966,"cuatrocientos cincuenta y dos millones novecientos setenta y seis mil novecientos sesenta y seis"],
 [924439602,"novecientos veinticuatro millones cuatrocientos treinta y nueve mil seiscientos dos"],
 [817038508,"ochocientos diecisiete millones treinta y ocho mil quinientos ocho"],
 [794533029,"setecientos noventa y cuatro millones quinientos treinta y tres mil veintinueve"],
 [957254528,"novecientos cincuenta y siete millones doscientos cincuenta y cuatro mil quinientos veintiocho"],
 [961950697,"novecientos sesenta y un millones novecientos cincuenta mil seiscientos noventa y siete"],
 [757085333,"setecientos cincuenta y siete millones ochenta y cinco mil trescientos treinta y tres"],
 [460129491,"cuatrocientos sesenta millones ciento veintinueve mil cuatrocientos noventa y un"],
 [320201544,"trescientos veinte millones doscientos un mil quinientos cuarenta y cuatro"],
 [898504064,"ochocientos noventa y ocho millones quinientos cuatro mil sesenta y cuatro"],
 [972747270,"novecientos setenta y dos millones setecientos cuarenta y siete mil doscientos setenta"],
 [138192421,"ciento treinta y ocho millones ciento noventa y dos mil cuatrocientos veintiun"],
 [219756517,"doscientos diecinueve millones setecientos cincuenta y seis mil quinientos diecisiete"],
 [430620644,"cuatrocientos treinta millones seiscientos veinte mil seiscientos cuarenta y cuatro"],
 [390118714,"trescientos noventa millones ciento dieciocho mil setecientos catorce"],
 [58503946,"cincuenta y ocho millones quinientos tres mil novecientos cuarenta y seis"],
 [446599381,"cuatrocientos cuarenta y seis millones quinientos noventa y nueve mil trescientos ochenta y un"],
 [181684280,"ciento ochenta y un millones seiscientos ochenta y cuatro mil doscientos ochenta"],
 [222832890,"doscientos veintidos millones ochocientos treinta y dos mil ochocientos noventa"],
 [916710029,"novecientos dieciseis millones setecientos diez mil veintinueve"],
 [624562067,"seiscientos veinticuatro millones quinientos sesenta y dos mil sesenta y siete"],
 [192206055,"ciento noventa y dos millones doscientos seis mil cincuenta y cinco"],
 [139225644,"ciento treinta y nueve millones doscientos veinticinco mil seiscientos cuarenta y cuatro"],
 [474877004,"cuatrocientos setenta y cuatro millones ochocientos setenta y siete mil cuatro"],
 [985596121,"novecientos ochenta y cinco millones quinientos noventa y seis mil ciento veintiun"],
 [379702885,"trescientos setenta y nueve millones setecientos dos mil ochocientos ochenta y cinco"],
 [194533591,"ciento noventa y cuatro millones quinientos treinta y tres mil quinientos noventa y un"],
 [713091437,"setecientos trece millones noventa y un mil cuatrocientos treinta y siete"],
 [251976353,"doscientos cincuenta y un millones novecientos setenta y seis mil trescientos cincuenta y tres"],
 [114494738,"ciento catorce millones cuatrocientos noventa y cuatro mil setecientos treinta y ocho"],
 [116033171,"ciento dieciseis millones treinta y tres mil ciento setenta y un"],
 [423070112, "cuatrocientos veintitres millones setenta mil ciento doce"],
 [494188893,"cuatrocientos noventa y cuatro millones ciento ochenta y ocho mil ochocientos noventa y tres"],
 [330064934,"trescientos treinta millones sesenta y cuatro mil novecientos treinta y cuatro"],
 [731452385,"setecientos treinta y un millones cuatrocientos cincuenta y dos mil trescientos ochenta y cinco"],
 [74566668,"setenta y cuatro millones quinientos sesenta y seis mil seiscientos sesenta y ocho"],
 [792524973,"setecientos noventa y dos millones quinientos veinticuatro mil novecientos setenta y tres"],
 [618329005,"seiscientos dieciocho millones trescientos veintinueve mil cinco"],
 [827150901,"ochocientos veintisiete millones ciento cincuenta mil novecientos un"],
 [391092549,"trescientos noventa y un millones noventa y dos mil quinientos cuarenta y nueve"],
 [729007780, "setecientos veintinueve millones siete mil setecientos ochenta"],
 [256648316,"doscientos cincuenta y seis millones seiscientos cuarenta y ocho mil trescientos dieciseis"],
 [481701574,"cuatrocientos ochenta y un millones setecientos un mil quinientos setenta y cuatro"],
 [51208088, "cincuenta y un millones doscientos ocho mil ochenta y ocho"],
 [717138899,"setecientos diecisiete millones ciento treinta y ocho mil ochocientos noventa y nueve"],
 [149717839,"ciento cuarenta y nueve millones setecientos diecisiete mil ochocientos treinta y nueve"],
 [124352286,"ciento veinticuatro millones trescientos cincuenta y dos mil doscientos ochenta y seis"],
 [403285720,"cuatrocientos tres millones doscientos ochenta y cinco mil setecientos veinte"],
 [504643023,"quinientos cuatro millones seiscientos cuarenta y tres mil veintitres"],
 [414724378,"cuatrocientos catorce millones setecientos veinticuatro mil trescientos setenta y ocho"],
 [513991752,"quinientos trece millones novecientos noventa y un mil setecientos cincuenta y dos"],
 [393792218,"trescientos noventa y tres millones setecientos noventa y dos mil doscientos dieciocho"],
 [392420087,"trescientos noventa y dos millones cuatrocientos veinte mil ochenta y siete"],
 [753756130,"setecientos cincuenta y tres millones setecientos cincuenta y seis mil ciento treinta"],
 [487848023,"cuatrocientos ochenta y siete millones ochocientos cuarenta y ocho mil veintitres"],
 [108242155,"ciento ocho millones doscientos cuarenta y dos mil ciento cincuenta y cinco"],
 [758726831,"setecientos cincuenta y ocho millones setecientos veintiseis mil ochocientos treinta y un"],
 [32153697,"treinta y dos millones ciento cincuenta y tres mil seiscientos noventa y siete"],
 [299689330,"doscientos noventa y nueve millones seiscientos ochenta y nueve mil trescientos treinta"],
 [437659993,"cuatrocientos treinta y siete millones seiscientos cincuenta y nueve mil novecientos noventa y tres"],
 [887045455,"ochocientos ochenta y siete millones cuarenta y cinco mil cuatrocientos cincuenta y cinco"],
 [330400212, "trescientos treinta millones cuatrocientos mil doscientos doce"],
 [703053787,"setecientos tres millones cincuenta y tres mil setecientos ochenta y siete"],
 [301171721,"trescientos un millones ciento setenta y un mil setecientos veintiun"],
 [693055432,"seiscientos noventa y tres millones cincuenta y cinco mil cuatrocientos treinta y dos"],
 [360980255,"trescientos sesenta millones novecientos ochenta mil doscientos cincuenta y cinco"],
 [376827160,"trescientos setenta y seis millones ochocientos veintisiete mil ciento sesenta"],
 [24682633,"veinticuatro millones seiscientos ochenta y dos mil seiscientos treinta y tres"],
 [931160701,"novecientos treinta y un millones ciento sesenta mil setecientos un"],
 [608417505,"seiscientos ocho millones cuatrocientos diecisiete mil quinientos cinco"],
 [136211070, "ciento treinta y seis millones doscientos once mil setenta"],
 [647900991,"seiscientos cuarenta y siete millones novecientos mil novecientos noventa y un"],
 [88494242,"ochenta y ocho millones cuatrocientos noventa y cuatro mil doscientos cuarenta y dos"],
 [229320257,"doscientos veintinueve millones trescientos veinte mil doscientos cincuenta y siete"],
 [523011016, "quinientos veintitres millones once mil dieciseis"],
 [385750734,"trescientos ochenta y cinco millones setecientos cincuenta mil setecientos treinta y cuatro"],
 [482113132,"cuatrocientos ochenta y dos millones ciento trece mil ciento treinta y dos"],
 [395143596,"trescientos noventa y cinco millones ciento cuarenta y tres mil quinientos noventa y seis"],
 [637694207,"seiscientos treinta y siete millones seiscientos noventa y cuatro mil doscientos siete"],
 [115636227,"ciento quince millones seiscientos treinta y seis mil doscientos veintisiete"],
 [292653027,"doscientos noventa y dos millones seiscientos cincuenta y tres mil veintisiete"],
 [860103590,"ochocientos sesenta millones ciento tres mil quinientos noventa"],
 [54698853,"cincuenta y cuatro millones seiscientos noventa y ocho mil ochocientos cincuenta y tres"],
 [710349775,"setecientos diez millones trescientos cuarenta y nueve mil setecientos setenta y cinco"],
 [297314478,"doscientos noventa y siete millones trescientos catorce mil cuatrocientos setenta y ocho"],
 [635598822,"seiscientos treinta y cinco millones quinientos noventa y ocho mil ochocientos veintidos"],
 [14719371,"catorce millones setecientos diecinueve mil trescientos setenta y un"],
 [129541125,"ciento veintinueve millones quinientos cuarenta y un mil ciento veinticinco"],
 [1000000, 'un millón'],
 [0, 'cero'],
 [10, 'diez']
]
